name: LOCI Summary
description: Fetch LOCI Summary Report and Insights
author: AuroraLabs

inputs:
  project:
    description: LOCI project name.
    required: true
  target:
    description: Version name.
    required: true
  base:
    description: Base version name. If provided, version is compared against it.
    required: false
  top-n-symbols:
    description: Number of symbols displayed in function insights - summary step
    required: true
    default: '5'

runs:
  using: node20
  main: dist/index.js