name: LOCI Version Resolver
description: Action that resolves project's version
author: AuroraLabs

inputs:
  project:
    description: Project name.
    required: true
  target:
    description: Version name.
    required: false
  base:
    description: Base version name. If provided, version is compared against it.
    required: false

outputs:
  target: 
    description: Project target version name used for this run.
  base:
    description: Project base version name (may be empty if context is not Pull Request).

runs:
  using: node20
  main: dist/index.js